### PR TITLE
Add configurable base controller class

### PR DESCRIPTION
**Pull request by elalemanyo**
Add `base_controller_class` accessor to ActiveHashcash. I think this may help when using the mountable dashboard.

### CODE REVIEW

**Comment by alexisbernard** [comment]
I never thought about doing that. That seems interesting to better integrate with other admin stuff. I will give it a try.

**Comment by elalemanyo** [comment]
@alexisbernard I think this is the best way to be able to integrate it in every application. The idea is inspired by [Mission Control - Jobs](https://github.com/rails/mission_control-jobs?tab=readme-ov-file#authentication-and-base-controller-class) 🙂

**Comment by alexisbernard** [comment]
Yes, it seems obvious that is the right way to do it. It felt like, why we did wrong for so long.

I have an error using using `config`:

```rb
config.active_hashcash.base_controller_class = "AdminController"

# railties-7.2.2/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `active_hashcash' for an instance of Rails::Application::Configuration (NoMethodError)
```

However it works using directly the attribute writer:

```rb
ActiveHashcash.base_controller_class = "Admin::BaseController"
```

With which version of Rails did you try?

**Comment by elalemanyo** [comment]
I tested it using a rails `7.2.2` project. But I have to admit I did it inside an `initializer` 😬
```ruby
ActiveHashcash.base_controller_class = "Admin::BaseController"
```

**Comment by elalemanyo** [comment]
Ok, I think that using `config.` would not work for `active_hashcash` 😔
Attempting to set `base_controller_class` using `config.active_hashcash.base_controller_class` in `config/application.rb` results in the undefined method error.
To configure `ActiveHashcash.base_controller_class` properly, you should set it directly within an `initializer`. This approach ensures that the configuration is applied after all necessary components have been loaded.

**Comment by alexisbernard** [comment]
Can you describe the new feature in changelog please? That would be perfect if you add the Unreleased heading since it's not present yet:

```
# Changelog of ActiveHashcash

## Unreleased

- DESCRIPTION HERE

## 0.3.2 (2024-08-29)
```

**Comment by elalemanyo** [comment]
@alexisbernard done 🙂

**Comment by alexisbernard** [comment]
Thanks for your contribution. I will copy this idea into ActiveAnalytics ;-)

**Comment by elalemanyo** [comment]
@alexisbernard As we also like ActiveAnalytics very much here it is: [PR](https://github.com/BaseSecrete/active_analytics/pull/14)

PS: We have not been able to test it much but it is quite similar to the other one, I hope there is no mistake. Let me know if I can help. Thank you very much for your help.

**Pull request merged**
